// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/shared"
	"net/http"
)

type CreateEnvironmentVariableResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created environment variable
	EnvironmentVariable *shared.EnvironmentVariable
}

func (c *CreateEnvironmentVariableResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateEnvironmentVariableResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateEnvironmentVariableResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateEnvironmentVariableResponse) GetEnvironmentVariable() *shared.EnvironmentVariable {
	if c == nil {
		return nil
	}
	return c.EnvironmentVariable
}
