// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteEnvironmentVariableRequest struct {
	// Environment variable key
	Key string `pathParam:"style=simple,explode=false,name=key"`
}

func (d *DeleteEnvironmentVariableRequest) GetKey() string {
	if d == nil {
		return ""
	}
	return d.Key
}

type DeleteEnvironmentVariableResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteEnvironmentVariableResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteEnvironmentVariableResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteEnvironmentVariableResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
