// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/shared"
	"net/http"
)

type GetEnvironmentVariableRequest struct {
	// Environment variable key
	Key string `pathParam:"style=simple,explode=false,name=key"`
}

func (g *GetEnvironmentVariableRequest) GetKey() string {
	if g == nil {
		return ""
	}
	return g.Key
}

type GetEnvironmentVariableResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Environment variable
	EnvironmentVariable *shared.EnvironmentVariable
}

func (g *GetEnvironmentVariableResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetEnvironmentVariableResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetEnvironmentVariableResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetEnvironmentVariableResponse) GetEnvironmentVariable() *shared.EnvironmentVariable {
	if g == nil {
		return nil
	}
	return g.EnvironmentVariable
}
