// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/shared"
	"net/http"
)

type ListEnvironmentGroupsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of environment groups
	EnvironmentGroupList *shared.EnvironmentGroupList
}

func (l *ListEnvironmentGroupsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListEnvironmentGroupsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListEnvironmentGroupsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListEnvironmentGroupsResponse) GetEnvironmentGroupList() *shared.EnvironmentGroupList {
	if l == nil {
		return nil
	}
	return l.EnvironmentGroupList
}
