// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/shared"
	"net/http"
)

type ListEnvironmentVariablesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of environment variables
	EnvironmentVariableList *shared.EnvironmentVariableList
}

func (l *ListEnvironmentVariablesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListEnvironmentVariablesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListEnvironmentVariablesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListEnvironmentVariablesResponse) GetEnvironmentVariableList() *shared.EnvironmentVariableList {
	if l == nil {
		return nil
	}
	return l.EnvironmentVariableList
}
