// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/shared"
	"net/http"
)

type PutEnvironmentGroupRequest struct {
	Name                          string                               `pathParam:"style=simple,explode=false,name=name"`
	EnvironmentGroupUpsertRequest shared.EnvironmentGroupUpsertRequest `request:"mediaType=application/json"`
}

func (p *PutEnvironmentGroupRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PutEnvironmentGroupRequest) GetEnvironmentGroupUpsertRequest() shared.EnvironmentGroupUpsertRequest {
	if p == nil {
		return shared.EnvironmentGroupUpsertRequest{}
	}
	return p.EnvironmentGroupUpsertRequest
}

type PutEnvironmentGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated group
	EnvironmentGroup *shared.EnvironmentGroup
}

func (p *PutEnvironmentGroupResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PutEnvironmentGroupResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PutEnvironmentGroupResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PutEnvironmentGroupResponse) GetEnvironmentGroup() *shared.EnvironmentGroup {
	if p == nil {
		return nil
	}
	return p.EnvironmentGroup
}
