// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/shared"
	"net/http"
)

type UpdateEnvironmentVariableRequest struct {
	// Environment variable key
	Key                              string                                  `pathParam:"style=simple,explode=false,name=key"`
	EnvironmentVariableUpdateRequest shared.EnvironmentVariableUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateEnvironmentVariableRequest) GetKey() string {
	if u == nil {
		return ""
	}
	return u.Key
}

func (u *UpdateEnvironmentVariableRequest) GetEnvironmentVariableUpdateRequest() shared.EnvironmentVariableUpdateRequest {
	if u == nil {
		return shared.EnvironmentVariableUpdateRequest{}
	}
	return u.EnvironmentVariableUpdateRequest
}

type UpdateEnvironmentVariableResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated environment variable
	EnvironmentVariable *shared.EnvironmentVariable
}

func (u *UpdateEnvironmentVariableResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateEnvironmentVariableResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateEnvironmentVariableResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateEnvironmentVariableResponse) GetEnvironmentVariable() *shared.EnvironmentVariable {
	if u == nil {
		return nil
	}
	return u.EnvironmentVariable
}
