// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EnvironmentGroupList struct {
	Items []EnvironmentGroup `json:"items"`
}

func (e *EnvironmentGroupList) GetItems() []EnvironmentGroup {
	if e == nil {
		return []EnvironmentGroup{}
	}
	return e.Items
}
