// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EnvironmentVariableList struct {
	Items []EnvironmentVariableListItem `json:"items"`
}

func (e *EnvironmentVariableList) GetItems() []EnvironmentVariableListItem {
	if e == nil {
		return []EnvironmentVariableListItem{}
	}
	return e.Items
}
