// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/internal/utils"
	"time"
)

type EnvironmentVariable struct {
	Key         string               `json:"key"`
	Type        EnvironmentValueType `json:"type"`
	Description *string              `json:"description,omitempty"`
	// Value is returned for String type, omitted for SecretString
	Value     *string   `json:"value,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (e EnvironmentVariable) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvironmentVariable) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnvironmentVariable) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *EnvironmentVariable) GetType() EnvironmentValueType {
	if e == nil {
		return EnvironmentValueType("")
	}
	return e.Type
}

func (e *EnvironmentVariable) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *EnvironmentVariable) GetValue() *string {
	if e == nil {
		return nil
	}
	return e.Value
}

func (e *EnvironmentVariable) GetCreatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.CreatedAt
}

func (e *EnvironmentVariable) GetUpdatedAt() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.UpdatedAt
}
