// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EnvironmentVariableUpdateRequest struct {
	// Type of variable. Used when creating a new variable. Defaults to String.
	Type        *EnvironmentValueType `json:"type,omitempty"`
	Value       *string               `json:"value,omitempty"`
	Description *string               `json:"description,omitempty"`
	Group       *string               `json:"group,omitempty"`
	// Whether the variable is protected from editing
	Protected *bool `json:"protected,omitempty"`
}

func (e *EnvironmentVariableUpdateRequest) GetType() *EnvironmentValueType {
	if e == nil {
		return nil
	}
	return e.Type
}

func (e *EnvironmentVariableUpdateRequest) GetValue() *string {
	if e == nil {
		return nil
	}
	return e.Value
}

func (e *EnvironmentVariableUpdateRequest) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *EnvironmentVariableUpdateRequest) GetGroup() *string {
	if e == nil {
		return nil
	}
	return e.Group
}

func (e *EnvironmentVariableUpdateRequest) GetProtected() *bool {
	if e == nil {
		return nil
	}
	return e.Protected
}
