// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EnvironmentVariableCreateRequest struct {
	Key         string               `json:"key"`
	Type        EnvironmentValueType `json:"type"`
	Description *string              `json:"description,omitempty"`
	Value       string               `json:"value"`
}

func (e *EnvironmentVariableCreateRequest) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *EnvironmentVariableCreateRequest) GetType() EnvironmentValueType {
	if e == nil {
		return EnvironmentValueType("")
	}
	return e.Type
}

func (e *EnvironmentVariableCreateRequest) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *EnvironmentVariableCreateRequest) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}
