// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EnvironmentGroupUpsertRequest struct {
	Description *string `json:"description,omitempty"`
}

func (e *EnvironmentGroupUpsertRequest) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}
