// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EnvironmentVariableCreateRequest struct {
	Key         string               `json:"key"`
	Type        EnvironmentValueType `json:"type"`
	Description *string              `json:"description,omitempty"`
	Group       *string              `json:"group,omitempty"`
	Value       *string              `json:"value,omitempty"`
	// Whether the variable is protected from editing
	Protected *bool `json:"protected,omitempty"`
}

func (e *EnvironmentVariableCreateRequest) GetKey() string {
	if e == nil {
		return ""
	}
	return e.Key
}

func (e *EnvironmentVariableCreateRequest) GetType() EnvironmentValueType {
	if e == nil {
		return EnvironmentValueType("")
	}
	return e.Type
}

func (e *EnvironmentVariableCreateRequest) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *EnvironmentVariableCreateRequest) GetGroup() *string {
	if e == nil {
		return nil
	}
	return e.Group
}

func (e *EnvironmentVariableCreateRequest) GetValue() *string {
	if e == nil {
		return nil
	}
	return e.Value
}

func (e *EnvironmentVariableCreateRequest) GetProtected() *bool {
	if e == nil {
		return nil
	}
	return e.Protected
}
