// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/provider/typeconvert"
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *EnvironmentVariableDataSourceModel) RefreshFromSharedEnvironmentVariable(ctx context.Context, resp *shared.EnvironmentVariable) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.Description = types.StringPointerValue(resp.Description)
		r.Key = types.StringValue(resp.Key)
		r.Type = types.StringValue(string(resp.Type))
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
		r.Value = types.StringPointerValue(resp.Value)
	}

	return diags
}

func (r *EnvironmentVariableDataSourceModel) ToOperationsGetEnvironmentVariableRequest(ctx context.Context) (*operations.GetEnvironmentVariableRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var key string
	key = r.Key.ValueString()

	out := operations.GetEnvironmentVariableRequest{
		Key: key,
	}

	return &out, diags
}
