// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/provider/typeconvert"
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-environment/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *EnvironmentVariableResourceModel) RefreshFromSharedEnvironmentVariable(ctx context.Context, resp *shared.EnvironmentVariable) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.Description = types.StringPointerValue(resp.Description)
		r.Key = types.StringValue(resp.Key)
		r.Type = types.StringValue(string(resp.Type))
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
		r.Value = types.StringPointerValue(resp.Value)
	}

	return diags
}

func (r *EnvironmentVariableResourceModel) ToOperationsDeleteEnvironmentVariableRequest(ctx context.Context) (*operations.DeleteEnvironmentVariableRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var key string
	key = r.Key.ValueString()

	out := operations.DeleteEnvironmentVariableRequest{
		Key: key,
	}

	return &out, diags
}

func (r *EnvironmentVariableResourceModel) ToOperationsGetEnvironmentVariableRequest(ctx context.Context) (*operations.GetEnvironmentVariableRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var key string
	key = r.Key.ValueString()

	out := operations.GetEnvironmentVariableRequest{
		Key: key,
	}

	return &out, diags
}

func (r *EnvironmentVariableResourceModel) ToOperationsUpdateEnvironmentVariableRequest(ctx context.Context) (*operations.UpdateEnvironmentVariableRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var key string
	key = r.Key.ValueString()

	environmentVariableUpdateRequest, environmentVariableUpdateRequestDiags := r.ToSharedEnvironmentVariableUpdateRequest(ctx)
	diags.Append(environmentVariableUpdateRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateEnvironmentVariableRequest{
		Key:                              key,
		EnvironmentVariableUpdateRequest: *environmentVariableUpdateRequest,
	}

	return &out, diags
}

func (r *EnvironmentVariableResourceModel) ToSharedEnvironmentVariableCreateRequest(ctx context.Context) (*shared.EnvironmentVariableCreateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var key string
	key = r.Key.ValueString()

	typeVar := shared.EnvironmentValueType(r.Type.ValueString())
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	var value string
	value = r.Value.ValueString()

	out := shared.EnvironmentVariableCreateRequest{
		Key:         key,
		Type:        typeVar,
		Description: description,
		Value:       value,
	}

	return &out, diags
}

func (r *EnvironmentVariableResourceModel) ToSharedEnvironmentVariableUpdateRequest(ctx context.Context) (*shared.EnvironmentVariableUpdateRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	typeVar := new(shared.EnvironmentValueType)
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		*typeVar = shared.EnvironmentValueType(r.Type.ValueString())
	} else {
		typeVar = nil
	}
	var value string
	value = r.Value.ValueString()

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	out := shared.EnvironmentVariableUpdateRequest{
		Type:        typeVar,
		Value:       value,
		Description: description,
	}

	return &out, diags
}
